### PR TITLE
Convert for loops to use forEach to clarify code intent.

### PR DESCRIPTION
**Pull request by robbyoconnor**
This implements what I suggested on 8e3fa169104b0c956214f12cfbb6313b355f6b5c

### CODE REVIEW

**Comment by robbyoconnor** [comment]
In addition to it looking nicer, it's much, much clearer as to what the code is doing now :)

**Comment by robbyoconnor** [comment]
This PR has warped a bit and removed (almost) all for loops when looping through arrays

**Comment by ScottLNorvell** [comment]
Hi @robbyoconnor. Thanks for the suggestion and for your interest in the project! I'm not sure this PR adds much value, so I am closing it for now. For loops are actually quite a bit faster than `Array#forEach`, and since the project iterates over so many arrays at each tick, I think keeping them for loops makes the most sense. Have a look at [this jsPerf](https://jsperf.com/for-vs-foreach/37) for reference.

**Comment by robbyoconnor** [comment]
That is completely okay :)

**Pull request closed without merging**
